language: node_js
cache: yarn
install:
  - yarn install --check-cache
  - yarn dlx cypress verify
  - yarn add --dev wait-on
script:
  - yarn stylelint "src/**/*.css" --quiet
  - yarn eslint "src/**/*.{js,ts,jsx,tsx}" --quiet
  - yarn start & wait-on http://localhost:8080 &
  - yarn test
  - kill $(jobs -p) || true

