language: node_js
cache: yarn
node_js:
  - "10.14.2"
install:
  - yarn install
  - yarn cypress verify
  - yarn add --dev codecov wait-on
script:
  - yarn lint
  - yarn test && codecov
  - yarn start & wait-on http://localhost:8080 &
  - yarn test:cypress-run
  - kill $(jobs -p) || true

