language: node_js
cache: npm
install:
  - npm ci
  - npx cypress verify
  - npm install -D codecov wait-on
script:
  - npm run lint
  - npm run test && codecov
  - npm run start & wait-on http://localhost:8080 &
  - npm run test:cypress-run
  - kill $(jobs -p) || true

